### PR TITLE
Update CI to use GitHub Actions

### PR DESCRIPTION
**Pull request by tzumainn**

### CODE REVIEW

**Review by mnbatra — APPROVED** [review]
Looks good

**Review by ljmcgann — COMMENTED** [review]
Why are we able to remove all these files? I get that the functionality is being replaced but I don't know enough about the tooling here to say if this does what we want

**Comment by tzumainn** [comment]
The files being removed are specifically for Travis CI; we're moving from that to GitHub actions, so those travis files should be removed as they'll no longer do anything.

**Comment by ljmcgann** [comment]
lgtm

**Review by ljmcgann — APPROVED** [review]

**Pull request merged**
