### PR TITLE
run tests in travis-ci

### PR DESCRIPTION
**Pull request by naved001**
change travis version to match whatever is specified in tox.ini

### CODE REVIEW

**Comment by naved001** [comment]
this time it looks like the tests, as run by tox, are failing. when run locally, they will pass sometimes and fail other times.

**Comment by tzumainn** [comment]
> this time it looks like the tests, as run by tox, are failing. when run locally, they will pass sometimes and fail other times.

Weird - I can't get them to fail at all. Can you try running the tests locally with https://github.com/CCI-MOC/esi-leap/pull/31/files applied, and see if they still sometimes fail?

**Comment by naved001** [comment]
> Failed 1 tests - output below:
> ==============================
> 
> esi_leap.tests.common.test_policy.PolicyTestCase.test_authorize_policy_not_registered
> -------------------------------------------------------------------------------------
> 
> Captured traceback:
> ~~~~~~~~~~~~~~~~~~~
>     Traceback (most recent call last):
> 
>       File "/home/naved/esi-leap/esi_leap/tests/common/test_policy.py", line 34, in test_authorize_policy_not_registered
>     self.assertRaises(
> 
>       File "/home/naved/esi-leap/.tox/py3/lib/python3.8/site-packages/testtools/testcase.py", line 489, in assertRaises
>     self.assertThat(our_callable, matcher)
> 
>       File "/home/naved/esi-leap/.tox/py3/lib/python3.8/site-packages/testtools/testcase.py", line 502, in assertThat
>     raise mismatch_error
> 
>     testtools.matchers._impl.MismatchError: <function authorize at 0x7f7663e16c10> returned True

ran it with the changed tox.ini and it still failed.

This is my tox version that I installed using pip3 (on ubuntu 20.04).
```
naved@naved-MS-7984:~/esi-leap$ tox --version
3.16.1 imported from /home/naved/.local/lib/python3.8/site-packages/tox/__init__.py
```

**Comment by naved001** [comment]
I rebased this PR. 

The two tests that are failing for me (and in travis) are:
```
esi_leap.tests.common.test_policy.PolicyTestCase.test_authorize_policy_not_registered
esi_leap.tests.common.test_policy.PolicyTestCase.test_unauthorized
```
Though when I run only those tests individually or the whole class they always pass.
```
tox -e py3 -- esi_leap.tests.common.test_policy.PolicyTestCase
```

**Pull request merged**
